CREATE TABLE RUN_INSTANCE (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null
);

insert into RUN_INSTANCE (name) values ('exo');
insert into RUN_INSTANCE (name) values ('exo2');